version: '3.1'

services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    volumes: 
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  wiremock:
    image: rodolpheche/wiremock
    ports:
      - 8080:8080
    volumes:
      - ./wiremock:/home/wiremock
