version: '3.1'

services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    expose:
     - 27017
    volumes: 
      - ./database:/data/db
    container_name: mongo
  redis:
    image: redis:5
    ports: 
      - 6379:6379
    expose:
     - 6379
    volumes:
      - ./database:/data
    container_name: redis

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8000:8000
    links:
      - mongo
      - redis
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "./backend:/code"

  frontend:
    build: ./frontend
    container_name: frontend
    command: ["npm", "start"]
    ports:
      - 4200:4200
      - 80:80
    links:
      - backend
