version: '3.1'

services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
    expose:
     - 27017
    volumes: 
      - ./database:/data/db
  redis:
    image: redis:5
    ports: 
      - 6379:6379
    expose:
     - 6379
    volumes:
      - ./database:/data
